---
- name: install
  apt: name=nginx state=latest update_cache=true cache_valid_time=3600
  tags:
  - packages

- name: enable service
  service: name=nginx enabled=yes state=started
  notify: restart-nginx
